### ISSUE TITLE
Suggestions from group Purple Boomerang Profreshers

### ISSUE THREAD

**Issue by Yeonhova** [jmai28/ReadyToRumble#2]
Your Readme is very well written and mostly goes along with what we did in class. I have some suggestions, but I may be wrong.
In the base case section it says
`If the starting position isLegal, return false. If it is not, continue with the recursive abstraction.`
Don't you mean if the starting position is not legal?

I have a comment on the recursive case:
```
else // recursive case
  walk south
    if isLegal // Cannot be a wall or a previous spot or not in the maze
      invoke recurisve abstraction
    walk back
```
If you check whether the next step is legal in the recursive case (which I don't think is "allowed"), doesn't that defeat the purpose of checking whether the current step is illegal in the base case.
I feel like the recursive case does not have to specify whether the next step is legal, because then the purpose of recursive backtracking is defeated.

Good job!

**Comment by jmai28** [comment]
Yea, the first part was a typo I forgot to fix.

Checking if the next step is legal is completely necessary as if isLegal fails, the recursive abstraction does not have to be invoked, improving efficiency. Why turn one step into multiple steps. The base case is really just to catch the very first starting position that the explorer starts on. If I remove the isLegal portion, the base case can actually snare on walls and thus incorrectly returning a false for the whole Maze Solver.

If you find anything wrong with what I have stated, feel free to reopen the issue. I will also clean up the ReadMe a bit. Feel free to point out anything.
